CC = g++
CFLAGS = -Wall -O3 --std=c++11

main.exe : main.o random.o integral.o coseno_es2.o
	$(CC) random.o coseno_es2.o integral.o main.o -o main.exe
main.o : main.cpp funzionebase.h coseno_es2.h random.h integral.h
	$(CC) -c main.cpp -o main.o $(CFLAGS)
random.o : random.cpp random.h funzionebase.h
	$(CC) -c random.cpp -o random.o $(CFLAGS)
coseno_es2.o : coseno_es2.cpp coseno_es2.h funzionebase.h
	$(CC) -c coseno_es2.cpp -o coseno_es2.o $(CFLAGS)
integral.o : integral.cpp integral.h random.h funzionebase.h
	$(CC) -c integral.cpp -o integral.o $(CFLAGS)
clean :
	rm *.o main.exe seed.out *.txt
